os: linux
language: shell

services:
  - docker

branches:
  only:
    - master

install:
  - curl -sSL https://raw.githubusercontent.com/acidgenomics/Rcheck/master/install | bash

jobs:
  include:
    - stage: test
      name: "bioc-release"
      script: image="acidgenomics/r-singlecell" tag="bioc-release" ./.Rcheck/docker
    - stage: test
      name: "bioc-devel"
      script: image="acidgenomics/r-singlecell" tag="bioc-devel" ./.Rcheck/docker
  allow_failures:
    - name: "bioc-devel"
  fast_finish: true

after_failure:
  - ./.Rcheck/docker-failure

notifications:
  email:
    recipients:
      - mike@steinbaugh.com
    on_success: change
    on_failure: change
