# Travis-CI configuration for Bioconductor packages
# https://docs.travis-ci.com/user/languages/r

# Single-cell configuration recommendations:
# https://github.com/satijalab/seurat/blob/master/.travis.yml
# https://github.com/satijalab/seurat/blob/release/3.0/.travis.yml
# https://github.com/drisso/zinbwave/blob/master/.travis.yml

language: r
cache: packages

# Necessary to install hdf5 update for Seurat/hdf5r (>= 1.8.13).
sudo: required

matrix:
  include:
  - os: linux
    r: release
  - os: osx
    r: release

branches:
  only:
  - master

env:
  global:
    # These are taken from the Seurat Travis CI config.
    # 1.10.4 is current. 1.8.17 used for Seurat CI.
    # https://www.hdfgroup.org/downloads/hdf5/
    - HDF5_VERSION=1.8.17
    - HDF5_RELEASE_URL="https://support.hdfgroup.org/ftp/HDF5/releases"
    - LINTR_COMMENT_BOT=true

before_install:
  - chmod +x travis_setup.sh
  - ./travis_setup.sh

# External dependencies.
# These are needed to install zinbwave on Linux.
addons:
  apt:
    packages:
      - gsl-bin
      - libgsl-dev
      # This is too old for hdf5r. Installing from source instead.
      # - libhdf5-dev

github_packages:
  - mjsteinbaugh/lintr

after_success:
  - Rscript -e 'lintr::lint_package()'

notifications:
  email:
    on_success: change
    on_failure: change
