# Travis-CI configuration for Bioconductor packages
# https://docs.travis-ci.com/user/languages/r

# Single-cell configuration recommendations:
# https://github.com/satijalab/seurat/blob/master/.travis.yml
# https://github.com/satijalab/seurat/blob/release/3.0/.travis.yml
# https://github.com/drisso/zinbwave/blob/master/.travis.yml

# hdf5r 1.0.1 won't install correctly.
# This package has major compilation issues across platforms.
#
# https://github.com/hhoeflin/hdf5r/issues/94#issuecomment-442890351
# https://github.com/hhoeflin/hdf5r/issues/97
#
# unable to load shared object '/home/travis/R/Library/hdf5r/libs/hdf5r.so':
# libhdf5_hl.so.10: cannot open shared object file: No such file or directory
# Installing 1.0.0 works on Azure Red Hat VM, and should work here too.
# This is a pain to manage, and switching to BioC 3.8 docker makes sense.

language: r
cache: packages

# Necessary to install hdf5 update for Seurat/hdf5r (>= 1.8.13).
sudo: required

matrix:
  include:
    - os: linux
      r: release
    # Disabled until macOS uses BioC 3.8 by default.
    # - os: osx
    #   r: release

branches:
  only:
    - master

# These are taken from the Seurat Travis CI config.
# 1.10.4 is current. 1.8.17 used for Seurat CI.
# https://www.hdfgroup.org/downloads/hdf5/
env:
  global:
    - HDF5_VERSION="1.8.17"
    - HDF5_RELEASE_URL="https://support.hdfgroup.org/ftp/HDF5/releases"
    - LD_LIBRARY_PATH="${LD_LIBRARY_PATH}:/usr/local/lib"

before_install:
  - chmod +x travis_setup.sh
  - ./travis_setup.sh

# External dependencies.
# These are needed to install zinbwave on Linux.
addons:
  apt:
    packages:
      - gsl-bin
      - libgsl-dev
      # This is too old for hdf5r. Installing from source instead.
      # - libhdf5-dev

env:
  global:
    - LINTR_COMMENT_BOT=true

github_packages:
  - steinbaugh/lintr

after_success:
  - Rscript -e 'lintr::lint_package()'

notifications:
  email:
    recipients:
      - mike@steinbaugh.com
    on_success: change
    on_failure: change
