language: general

services:
  - docker

branches:
  only:
    - master

install:
  - curl -sSL https://raw.githubusercontent.com/acidgenomics/Rcheck/master/install | bash

before_script:
    # Avoid BiocCheck > checkCodingPractice > checkLogicalUseFiles error.
  - touch inst/rmarkdown/templates/{seurat-clustering,seurat-markers,seurat-per-cluster-analysis}/skeleton/_{footer,header,links}.Rmd

jobs:
  include:
    - stage: test
      name: "bioc-release"
      script: image="singlecell" tag="bioc-release" ./.Rcheck/docker
    - stage: test
      name: "bioc-devel"
      script: image="singlecell" tag="bioc-devel" ./.Rcheck/docker

matrix:
  allow_failures:
    - name: "bioc-devel"
  fast_finish: true

after_failure:
  - ./.Rcheck/docker-failure

notifications:
  email:
    recipients:
      - mike@steinbaugh.com
    on_success: change
    on_failure: change
