# Travis-CI configuration for Bioconductor packages
# https://docs.travis-ci.com/user/languages/r

# Single-cell configuration recommendations:
# https://github.com/satijalab/seurat/blob/master/.travis.yml
# https://github.com/satijalab/seurat/blob/release/3.0/.travis.yml
# https://github.com/drisso/zinbwave/blob/master/.travis.yml

# hdf5r 1.0.1 won't install correctly.
# This package has major compilation issues across platforms.
#
# https://github.com/hhoeflin/hdf5r/issues/94#issuecomment-442890351
# https://github.com/hhoeflin/hdf5r/issues/97
#
# unable to load shared object '/home/travis/R/Library/hdf5r/libs/hdf5r.so':
# libhdf5_hl.so.10: cannot open shared object file: No such file or directory
#
# Installing 1.0.0 works on Azure Red Hat VM, and should work here too.
# This is a pain to manage, and switching to BioC 3.8 docker makes sense.

language: r
cache: packages

# Necessary to build and install hdf5 from source.
sudo: required

matrix:
  include:
    - os: linux
      r: release
    # Disabled until macOS image is updated to BioC 3.8.
    # - os: osx
    #   r: release

branches:
  only:
    - master

# https://docs.travis-ci.com/user/environment-variables/
env:
  global:
    - HDF5_RELEASE_URL="https://support.hdfgroup.org/ftp/HDF5/releases"
    - HDF5_VERSION="1.10.4"
    - LD_LIBRARY_PATH="${LD_LIBRARY_PATH}:/usr/local/lib"
    - LINTR_COMMENT_BOT=true

before_install:
  - chmod +x travis_setup.sh
  - ./travis_setup.sh

# External dependencies.
# These are needed to install zinbwave on Linux.
addons:
  apt:
    packages:
      - gsl-bin
      - libgsl-dev

github_packages:
  - steinbaugh/lintr

after_success:
  - Rscript -e 'lintr::lint_package()'

notifications:
  email:
    recipients:
      - mike@steinbaugh.com
    on_success: change
    on_failure: change
