# Travis-CI configuration for Bioconductor packages
# https://docs.travis-ci.com/user/languages/r

language: r
cache: packages

r:
  - bioc-release
  # - bioc-devel

os:
  # - linux
  - osx

matrix:
  exclude:
  - os: osx
    r: bioc-devel

# blocklist
# branches:
#   except:
#   - develop

# safelist
# branches:
#   only:
#   - master

env:
  global:
    - LINTR_COMMENT_BOT=true

# r_build_args: "--no-build-vignettes"
# r_check_args: "--no-vignettes"

# Set true before submission to Bioconductor
warnings_are_errors: true

# Temporarily enable when caching Bioconductor packages
script: true

r_packages:
  - covr
bioc_packages:
  - BiocCheck
  - EnsDb.Hsapiens.v75
r_github_packages:
  - jimhester/lintr

after_success:
  - Rscript -e 'lintr::lint_package()'
  - Rscript -e 'covr::codecov()'
  - R CMD BiocCheck .

notifications:
  email:
    recipients:
      - mike@steinbaugh.com
    on_success: change
    on_failure: always
