language: general

services:
  - docker

branches:
  only:
    - master

before_script:
  - chmod +x *.sh
    # Avoid BiocCheck > checkCodingPractice > checkLogicalUseFiles error.
  - touch inst/rmarkdown/templates/seurat-{clustering,markers,per-cluster-analysis}/skeleton/_{footer,header,links}.Rmd

jobs:
  include:
    - stage: test
      name: "Docker: Bioconductor 3.9"
      script: image="singlecell" tag="bioc-3.9" ./docker.sh
    - stage: test
      name: "Docker: Bioconductor 3.8"
      script: image="singlecell" tag="bioc-3.8" ./docker.sh

matrix:
  fast_finish: true

after_failure:
  - ./docker-failure.sh

notifications:
  email:
    recipients:
      - mike@steinbaugh.com
    on_success: change
    on_failure: change
